### ISSUE TITLE
使用的fake api，没有任何回复

### ISSUE THREAD

**Issue by jinde98** [daishuge/fakegpt_with_history#1]
我使用自己的fk-XXX，调用fake api，没有任何报错，但是没任何结果输出，监视chunk变量，一直为空，没有备赋值。
这是在vscode中运行的
![image](https://github.com/daishuge/-fakegpt-with-history/assets/127750182/94cd9d74-5864-439a-a81d-854e1d9da1cc)
这是在python运行的
![image](https://github.com/daishuge/-fakegpt-with-history/assets/127750182/aa57bb0f-ce9b-4ca3-8cdf-c63c5625cf8f)
希望能得到回复

**Comment by daishuge** [comment]
![image](https://github.com/daishuge/-fakegpt-with-history/assets/122254868/02591af9-6507-413c-8b51-343c36d6e702)
你好,在我这里是有的,也许是因为你的api的问题?你可以尝试一下我的:
```
fk-FCHVDJh1X-2HeS24Yla_Ejg03qJBdWaDOd-Jzy3PKTk
```
(github小透明第一次收到一个issues,惊喜)

**Comment by daishuge** [comment]
前面在vscode中运行,我补一个在cmd运行的:
![image](https://github.com/daishuge/-fakegpt-with-history/assets/122254868/d3c3eb46-993a-4bd0-803c-88416c11ff1f)

**Comment by jinde98** [comment]
> ![image](https://user-images.githubusercontent.com/122254868/277306802-02591af9-6507-413c-8b51-343c36d6e702.png) 你好,在我这里是有的,也许是因为你的api的问题?你可以尝试一下我的:
> 
> ```
> fk-FCHVDJh1X-2HeS24Yla_Ejg03qJBdWaDOd-Jzy3PKTk
> ```
> 
> (github小透明第一次收到一个issues,惊喜)
用了你的fk key,果然可以。原来是我的账户问题，我账号可以在openai使用，但最近是无法在pandora项目使用了。感谢了

**Comment by daishuge** [comment]
好哒,再见,顺便说一句,最近pandora的一些网址好像被墙了,具体参考pandora哈

**Comment by jinde98** [comment]
好的，之前想用pandora的代码库来完成api 调用，一直没弄成，现在换你的fk也是可以了。
再次感谢，终于让我知道问题在哪里了
```python
from pandora.turbo.chat import TurboGPT # 导入 TurboGPT 之前要安装pandora
import uuid

def talking():
    API_KEY = {'key': 'fk-FCHVDJh1X-2HeS24Yla_Ejg03qJBdWaDOd-Jzy3PKTk'}
    MODEL = 'gpt-3.5-turbo'
    chatgpt = TurboGPT(API_KEY)
    status, heards, generator = chatgpt.talk('你是谁', MODEL, str(uuid.uuid4()), str(uuid.uuid4()))
    print(status)
    if 200 == status:
        for item in generator: # 遍历生成器
            pass
        text_content = item['message']['content']['parts'][0] # 提取文本
        conversation_id = item['conversation_id']
        parent_message_id = item['message']['id']
        print("chatgpt: ",text_content)
        


if __name__ == '__main__':
    # query = input("You: ")
    talking()
```

**Comment by daishuge** [comment]
谢谢,又帮助了一个未来的大佬
也可以尝试一下我的另一个项目:https://github.com/daishuge/qqgpt_basic

**Comment by jinde98** [comment]
看到了，也是我想要的，感谢分享。还有那个search_gpt，也是不错的

**Comment by daishuge** [comment]
> text_content = item['message']['content']['parts'][0] # 提取文本

请问这个代码出处可以麻烦发一下嘛?缩进有点乱
再次感谢你对我的支持♥

**Comment by jinde98** [comment]
这个代码自己写的啊，复制上来就没缩进，def talking如下：
![image](https://github.com/daishuge/-fakegpt-with-history/assets/127750182/a5540e65-b6cb-431a-ac89-164a7fcb8084)

我先把item（就是generator生成器的内容）这个打印出来，发现一个json格式的，我就取item下key中各个值啊，这个就是text_contect来处啊。item打印出来如下：
![image](https://github.com/daishuge/-fakegpt-with-history/assets/127750182/a8174501-883c-4140-b653-93c153dcd372)

**Comment by daishuge** [comment]
非常感谢!
爱来自瓷器
