### ISSUE TITLE
有没有会做ui的大佬?

### ISSUE THREAD

**Issue by daishuge** [daishuge/fakegpt_with_history#8]
命令行界面太丑了...想做一个带ui界面的,但流式输出一直搞不定

请问有没有哪位大佬会ui的?

希望万能的github给我答案
![image](https://github.com/daishuge/fakegpt_with_history/assets/122254868/64853b6c-245f-4db1-83eb-1cf456d816de)

**Comment by snowy-yang** [comment]
没有

**Comment by daishuge** [comment]
让你说话了吗(雾

yao ***@***.***> 于2023年11月1日周三 21:02写道：

**Comment by snowy-yang** [comment]
现在有了

**Comment by daishuge** [comment]
dans1现在不需要了(

yao ***@***.***> 于2023年11月5日周日 14:58写道：

**Comment by daishuge** [comment]
> 但是现在不需要了(
